table Scenario
	lineageTag: dc8ddf71-eb3e-4b31-8a23-88350b0138f7
	sourceLineageTag: [dbo].[Scenario]

	measure Scenario = __Fn_PnL_Sum_Subtotal_and_Blanks( CALCULATE( SUM( Scenario[Creditlessdebit] ) ) )
		formatString: #,###;(#,###);
		lineageTag: ab07abc0-636d-4694-a3b8-f9d17762ff69

	measure Date = CONVERT( CALCULATE( MAX( 'effectivedate'[FiscalDate] ) ), STRING )
		lineageTag: fd30b897-0af2-4f1a-b4b4-c6b538d53537

	column EffectiveDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: f2c62809-30b0-408c-9eca-b7fde072b5ad
		sourceLineageTag: EffectiveDate
		summarizeBy: none
		sourceColumn: EffectiveDate

		annotation SummarizationSetBy = Automatic

	column AccountKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 64490ce6-91f3-4d7a-8707-31070283b49b
		sourceLineageTag: AccountKey
		summarizeBy: none
		sourceColumn: AccountKey

		annotation SummarizationSetBy = Automatic

	column ScenarioKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 49381d76-f8be-43f5-aa54-7b8c0978aa6b
		sourceLineageTag: ScenarioKey
		summarizeBy: count
		sourceColumn: ScenarioKey

		annotation SummarizationSetBy = Automatic

	column LegalEntityKey
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: b58652b7-2f48-40b1-bbf0-41ea5a31eff1
		sourceLineageTag: LegalEntityKey
		summarizeBy: count
		sourceColumn: LegalEntityKey

		annotation SummarizationSetBy = Automatic

	column Creditlessdebit
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: ede37669-5768-4cd4-b1c7-deceba24e056
		sourceLineageTag: Creditlessdebit
		summarizeBy: sum
		sourceColumn: Creditlessdebit

		annotation SummarizationSetBy = Automatic

	column ScenarioPK
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: ae0d910a-2551-4c69-9f1e-47f3d4fb9fed
		sourceLineageTag: ScenarioPK
		summarizeBy: sum
		sourceColumn: ScenarioPK

		annotation SummarizationSetBy = Automatic

	column MSSQL_System_Uniquifier_126623494
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 1c9afe11-5960-4fe6-ae31-2a980de3d27a
		sourceLineageTag: MSSQL_System_Uniquifier_126623494
		summarizeBy: sum
		sourceColumn: MSSQL_System_Uniquifier_126623494

		annotation SummarizationSetBy = Automatic

	partition Scenario = entity
		mode: directLake
		source
			entityName: Scenario
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

