table Account
	lineageTag: ae89694a-e279-474b-b076-e37b6bfb5c08

	column 'Account Key'
		dataType: int64
		isHidden
		isKey
		formatString: 0
		lineageTag: cc4c5de4-24bc-4979-bb35-c541693ded99
		summarizeBy: none
		sourceColumn: Account Key

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column 'Account Number and Name'
		dataType: string
		lineageTag: ff635237-aeac-4798-ad8c-e5be13f5a405
		summarizeBy: none
		sourceColumn: Account Number and Name

		annotation SummarizationSetBy = Automatic

	column 'Account Type'
		dataType: string
		isHidden
		lineageTag: 23f68320-f8bc-4f51-a6b2-99f9f73613c6
		summarizeBy: none
		sourceColumn: Account Type

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS","UNNECESSARY_COLUMNS"]}

	column 'Account Type Indicator'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ff118003-7ef1-48f5-82f8-4a42639bc2bd
		summarizeBy: sum
		sourceColumn: Account Type Indicator

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	column Income_Statement_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7a9dee36-b56d-4d77-b4ef-dc9b1f5f9675
		summarizeBy: none
		sourceColumn: Income_Statement_Key

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ISAVAILABLEINMDX_FALSE_NONATTRIBUTE_COLUMNS"]}

	partition Account = m
		mode: import
		source = ```
				let
				    Source = Binary.FromText(
				 
				 "QWNjb3VudCBLZXksQWNjb3VudCBOdW1iZXIgYW5kIE5hbWUsQWNjb3VudCBUeXBlLEFjY291bnQgVHlwZSBJbmRpY2F0b3IsSW5jb21lX1N0YXRlbWVudF9LZXkKMTAxMDAsMTAxMDAgLSBSZXZlbnVlLFJldmVudWUsMSwxMDIKMTAxMTAsMTAxMTAgLSBSZXZlbnVlLFJldmVudWUsMSwxMDIKMTAxMjAsMTAxMjAgLSBSZXZlbnVlLFJldmVudWUsMSwxMDIKMTAxMzAsMTAxMzAgLSBSZXZlbnVlLFJldmVudWUsMSwxMDIKMTAyMDAsMTAyMDAgLSBSZXZlbnVlLFJldmVudWUsMSwxMDMKMTAyMTAsMTAyMTAgLSBSZXZlbnVlLFJldmVudWUsMSwxMDMKMTAyMjAsMTAyMjAgLSBSZXZlbnVlLFJldmVudWUsMSwxMDMKMTAyMzAsMTAyMzAgLSBSZXZlbnVlLFJldmVudWUsMSwxMDMKMjAxMDAsMjAxMDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDcKMjAxMTAsMjAxMTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDcKMjAxMjAsMjAxMjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDcKMjAxMzAsMjAxMzAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDcKMjAxNDAsMjAxNDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDcKMjAyMDAsMjAyMDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDgKMjAyMTAsMjAyMTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDgKMjAyMjAsMjAyMjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDgKMjAyMzAsMjAyMzAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDgKMjAyNDAsMjAyNDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDgKMzAxMDAsMzAxMDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKMzAxMTAsMzAxMTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKMzAxMjAsMzAxMjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKMzAxMzAsMzAxMzAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKMzAxNDAsMzAxNDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKMzAxNTAsMzAxNTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKMzAxNjAsMzAxNjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKMzAxNzAsMzAxNzAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKMzAxODAsMzAxODAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKNDAxMDAsNDAxMDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKNDAxMTAsNDAxMTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKNDAxMjAsNDAxMjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKNDAxMzAsNDAxMzAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKNTAxMDAsNTAxMDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNTAxMTAsNTAxMTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNTAxMjAsNTAxMjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNTAxMzAsNTAxMzAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNTAxNDAsNTAxNDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNTAxNTAsNTAxNTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNTAxNjAsNTAxNjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNjAxMDAsNjAxMDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNjAxMTAsNjAxMTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNjAxMjAsNjAxMjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNzAxMDAsNzAxMDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTUKNzAxMTAsNzAxMTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTUKNzAxMjAsNzAxMjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTUKNzAxMzAsNzAxMzAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTUKNzAxNDAsNzAxNDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTUKNzA0MDAsNzA0MDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTUKNzA0MTAsNzA0MTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTUKNzA0MjAsNzA0MjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTUKNzA0MzAsNzA0MzAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTUKMTA3MTAsMTA3MTAgLSBPdGhlciBpbmNvbWUsUmV2ZW51ZSwxLDEyMAoxMDcyMCwxMDcxMCAtIE90aGVyIGluY29tZSxSZXZlbnVlLDEsMTIwCjgwMTAwLDgwMTAwIC0gRXhwZW5kaXR1cmUsRXhwZW5kaXR1cmUsLTEsMTIzCjgwMTEwLDgwMTEwIC0gRXhwZW5kaXR1cmUsRXhwZW5kaXR1cmUsLTEsMTIzCjgwMTIwLDgwMTIwIC0gRXhwZW5kaXR1cmUsRXhwZW5kaXR1cmUsLTEsMTIzCjgwMTMwLDgwMTMwIC0gRXhwZW5kaXR1cmUsRXhwZW5kaXR1cmUsLTEsMTIzCg=="
				        , BinaryEncoding.Base64),
				    #"Imported CSV" = Csv.Document(Source,[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Account Key", Int64.Type}, {"Account Number and Name", type text}, {"Account Type", type text}, {"Account Type Indicator", Int64.Type}, {"Income_Statement_Key", Int64.Type}})
				
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation TabularEditor_TableGroup = Dimensions

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["SNOWFLAKE_SCHEMA_ARCHITECTURE"]}

