[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
shared Account = let
    Source = Binary.FromText(
 
 "QWNjb3VudCBLZXksQWNjb3VudCBOdW1iZXIgYW5kIE5hbWUsQWNjb3VudCBUeXBlLEFjY291bnQgVHlwZSBJbmRpY2F0b3IsSW5jb21lX1N0YXRlbWVudF9LZXkKMTAxMDAsMTAxMDAgLSBSZXZlbnVlLFJldmVudWUsMSwxMDIKMTAxMTAsMTAxMTAgLSBSZXZlbnVlLFJldmVudWUsMSwxMDIKMTAxMjAsMTAxMjAgLSBSZXZlbnVlLFJldmVudWUsMSwxMDIKMTAxMzAsMTAxMzAgLSBSZXZlbnVlLFJldmVudWUsMSwxMDIKMTAyMDAsMTAyMDAgLSBSZXZlbnVlLFJldmVudWUsMSwxMDMKMTAyMTAsMTAyMTAgLSBSZXZlbnVlLFJldmVudWUsMSwxMDMKMTAyMjAsMTAyMjAgLSBSZXZlbnVlLFJldmVudWUsMSwxMDMKMTAyMzAsMTAyMzAgLSBSZXZlbnVlLFJldmVudWUsMSwxMDMKMjAxMDAsMjAxMDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDcKMjAxMTAsMjAxMTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDcKMjAxMjAsMjAxMjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDcKMjAxMzAsMjAxMzAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDcKMjAxNDAsMjAxNDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDcKMjAyMDAsMjAyMDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDgKMjAyMTAsMjAyMTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDgKMjAyMjAsMjAyMjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDgKMjAyMzAsMjAyMzAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDgKMjAyNDAsMjAyNDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMDgKMzAxMDAsMzAxMDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKMzAxMTAsMzAxMTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKMzAxMjAsMzAxMjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKMzAxMzAsMzAxMzAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKMzAxNDAsMzAxNDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKMzAxNTAsMzAxNTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKMzAxNjAsMzAxNjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKMzAxNzAsMzAxNzAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKMzAxODAsMzAxODAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKNDAxMDAsNDAxMDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKNDAxMTAsNDAxMTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKNDAxMjAsNDAxMjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKNDAxMzAsNDAxMzAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTMKNTAxMDAsNTAxMDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNTAxMTAsNTAxMTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNTAxMjAsNTAxMjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNTAxMzAsNTAxMzAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNTAxNDAsNTAxNDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNTAxNTAsNTAxNTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNTAxNjAsNTAxNjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNjAxMDAsNjAxMDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNjAxMTAsNjAxMTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNjAxMjAsNjAxMjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTQKNzAxMDAsNzAxMDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTUKNzAxMTAsNzAxMTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTUKNzAxMjAsNzAxMjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTUKNzAxMzAsNzAxMzAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTUKNzAxNDAsNzAxNDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTUKNzA0MDAsNzA0MDAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTUKNzA0MTAsNzA0MTAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTUKNzA0MjAsNzA0MjAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTUKNzA0MzAsNzA0MzAgLSBFeHBlbmRpdHVyZSxFeHBlbmRpdHVyZSwtMSwxMTUKMTA3MTAsMTA3MTAgLSBPdGhlciBpbmNvbWUsUmV2ZW51ZSwxLDEyMAoxMDcyMCwxMDcxMCAtIE90aGVyIGluY29tZSxSZXZlbnVlLDEsMTIwCjgwMTAwLDgwMTAwIC0gRXhwZW5kaXR1cmUsRXhwZW5kaXR1cmUsLTEsMTIzCjgwMTEwLDgwMTEwIC0gRXhwZW5kaXR1cmUsRXhwZW5kaXR1cmUsLTEsMTIzCjgwMTIwLDgwMTIwIC0gRXhwZW5kaXR1cmUsRXhwZW5kaXR1cmUsLTEsMTIzCjgwMTMwLDgwMTMwIC0gRXhwZW5kaXR1cmUsRXhwZW5kaXR1cmUsLTEsMTIzCg=="
        , BinaryEncoding.Base64),
    #"Imported CSV" = Csv.Document(Source,[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Account Key", Int64.Type}, {"Account Number and Name", type text}, {"Account Type", type text}, {"Account Type Indicator", Int64.Type}, {"Income_Statement_Key", Int64.Type}})

in
    #"Changed Type";
