table _Measures
	lineageTag: 10929eda-b6c4-43e5-96cb-53323cd7c315

	measure 'Basic Actuals' = __Fn_PnL_Sum_Subtotal_and_Blanks( SUM( 'ledger'[CreditlessdebitatGlobalFx]) )
		formatString: #,##0,;(#,##0,);
		displayFolder: Metrics
		lineageTag: 8fdd224c-9cf7-4a78-b55b-a42e564163a2

		annotation PBI_FormatHint = {"isCustom":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["INTEGER_FORMATTING"]}

	measure 'Basic Plan' = __Fn_PnL_ShowScenario( SUM( Scenario[Creditlessdebit] ) )
		formatString: " #,##0,;(#,##0,);"
		displayFolder: Metrics
		lineageTag: 1b61aeee-9368-4e1a-8d82-4c58d4870279

		annotation PBI_FormatHint = {"isCustom":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["INTEGER_FORMATTING"]}

	measure 'Var, #' = __Fn_PnL_HideVariances( [Basic Actuals], [Basic Plan] )
		formatString: " +#,##0,;-#,##0,;"
		displayFolder: Variance
		lineageTag: b6a97882-795b-459e-9862-174c0eeb5d9b

		annotation PBI_FormatHint = {"isCustom":true}

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["INTEGER_FORMATTING"]}

	measure 'Var, %' = DIVIDE( [Var, #], [Basic Actuals] )
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Variance
		lineageTag: 804429fc-827b-4643-85ab-09ac6f1f07e1

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Var, Text Highlight' = __Fn_PnL_Variance_Highlights( [Var, #] )
		formatString: 0
		displayFolder: Variance\Highlight
		lineageTag: c67e4049-283f-49bb-a1f9-6776fa9d15b1

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["INTEGER_FORMATTING"]}

	column Column1
		dataType: string
		lineageTag: 9636eb34-5016-4618-96e8-2ba840aa71a5
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation TabularEditor_TableGroup = Disconnected

